<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
//remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );

/*remove_action ('genesis_loop', 'genesis_do_loop'); // Remove the standard loop
add_action( 'genesis_loop', 'custom_do_grid_loop' ); // Add custom loop
function custom_do_grid_loop(){
    echo '<h4>' . get_the_title() . '</h4>';

}*/


// Customize the post info function
add_filter( 'genesis_post_info', 'post_info_filter' );
function post_info_filter($post_info) {
	$post_info = '[post_date]';
	return $post_info;
}

// Remove the post info function
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );



add_action( 'genesis_entry_content', 'sk_remove_post_meta' );
/**
 * Remove Post Meta in Entry Footer site-wide excerpt on static Pages.
 *
 * @author Sridhar Katakam
 * @link   http://sridharkatakam.com/remove-post-meta-entry-footer-genesis/
 */
function sk_remove_post_meta() {
	if ( is_singular( 'page' ) ) {
		return;
	}

	remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_open', 5 );
	remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_close', 15 );
	remove_action( 'genesis_entry_footer', 'genesis_post_meta' );
}


genesis();
